{% set name = "ydata-profiling" %}
{% set version = "4.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-profiling-{{ version }}.tar.gz
  sha256: cb73e0b2d48f67b678c633b970fd3abd9d3ffab5c69b1dd053bf71595b84ef51

build:
  entry_points:
    - ydata_profiling = ydata_profiling.controller.console:main
    - pandas_profiling = ydata_profiling.controller.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - pip
  run:
    - python >=3.8,<3.13
    - scipy >=1.4.1,<1.14
    - pandas >1.1,<3,!=1.4.0
    - matplotlib-base >=3.5,<3.10
    - pydantic >=2
    - pyyaml >=5.0.0,<6.1
    - jinja2 >=2.11.1,<3.2
    - visions >=0.7.5, <0.7.7
    - numpy >=1.16.0,<2.2
    - htmlmin ==0.1.12
    - phik >=0.11.1,<0.13
    - requests >=2.24.0,<3
    - tqdm >=4.48.2,<5
    - seaborn-base >=0.10.1,<0.14
    - multimethod >=1.4,<2
    - statsmodels >=0.13.2,<1
    - typeguard >=3,<5
    - imagehash ==4.3.1
    - wordcloud >=1.9.3
    - dacite >=1.8
    - numba >=0.56.0,<1

  run_constrained:
    - jupyter-client >=5.3.4
    - jupyter-core >=4.6.3
    - ipywidgets >=7.5.1
    - tangled-up-in-unicode ==0.2.0

test:
  imports:
    - pandas_profiling
    - ydata_profiling
  commands:
# Disabling pip check -   ydata-profiling 0.0.dev0 has requirement wordcloud>=1.9.1, but you have wordcloud 0.0. even though wordcloud >=1.9.1 is used
    - pip check
    - ydata_profiling --help
    - pandas_profiling --help
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-profiling
  summary: Generate profile report for pandas DataFrame
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://ydata-profiling.ydata.ai

extra:
  recipe-maintainers:
    - rxm7706
